######################################### SECTION 1 ################################################
# This section will build and release a clean version of Rubeus
name: CleanRubeus
on:
  push:
    branches:
      - master
jobs:
  CleanRubeus:
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'

      - name: Restore and Build
        run: |
          nuget restore
          dotnet build --configuration Release
