name: Read Changelog

on:
  push:
    branches:
      - master

jobs:
  read_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: rsecurity12/Rubeus

    - name: List items
      id: list_items
      run: |
        pwd && ls

    - name: Read CHANGELOG content
      run: |
        changelog_content=$(cat CHANGELOG.md)
        echo "$changelog_content"

    - name: Read All Changelog Versions
      run: |
        all_versions=$(grep -oP '^## \[\K[^\]]+' CHANGELOG.md)
        echo "All Changelog Versions: $all_versions"
      shell: bash

    - name: Read Latest Changelog Version
      run: |
        latest_version=$(grep -oP '^## \[\K[^\]]+' CHANGELOG.md | head -n 1)
        echo "Latest Changelog Version: $latest_version"
      shell: bash
