name: Read Changelog

on:
  push:
    branches:
      - master

jobs:
  read_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read Changelog
      id: read_changelog
      run: |
        # Read the contents of changelog.md
        changelog_content=$(cat changelog.md)

        # Extract the latest version using a regular expression
        latest_version=$(echo "$changelog_content" | grep -oP '^## \K[^\s]+' | head -n 1)
        
        # Print the latest version
        echo "Latest Version: $latest_version"

        # Set the latest version as an output variable
        echo "::set-output name=latest_version::$latest_version"
    
    - name: Use the Latest Version
      run: |
        # Access the latest version from the previous step's output
        echo "The latest version is ${{ steps.read_changelog.outputs.latest_version }}"
