name: Read Changelog

on:
  push:
    branches:
      - master

jobs:
  read_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: rsecurity12/Rubeus

    - name: List items
      id: list_items
      run: |
        pwd && ls

    
