on:  # Specifies the event triggering the workflow
  workflow_call:  # Indicates that this is a reusable workflow


jobs:
  CleanRubeus:
    runs-on: windows-2019

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'

      - name: Restore and Build
        run: |
          nuget restore
          dotnet build --configuration Release
