name: confuserExBuilder

on:
  push:
    branches:
      - '*'
  
jobs:
  build_and_release_ConfuserEXRubeus:
    runs-on: windows-2019
    steps:   
# ---------- Build & release Clean Rubeus version ----------  
      - name: Checkout Rubeus
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/Rubeus

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rubeus-artifacts
          path: "D:\\a\\Rubeus\\Rubeus\\Rubeus\\bin\\Release\\Rubeus.exe"
          
# ---------- Build & release ConfuserEXRubeus version ----------  
      - name: Checkout ConfuserEx
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/ConfuserEx

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: rubeus-artifacts
          
      - name: Debug Information
        run: |
          Get-ChildItem -Recurse
          Get-Location
          
      - name: Create a .crproj file
        run: |
          $xml = @'
            <project outputDir="D:\\a\\Rubeus\\Rubeus\\Confused" baseDir="D:\\a\\Rubeus\\Rubeus" xmlns="http://confuser.codeplex.com">
                <module path="Rubeus.exe">
                    <rule pattern="true" preset="maximum" inherit="false">
                      <protection id="anti debug" />
                      <protection id="anti dump" />
                      <protection id="anti ildasm" />
                      <protection id="anti tamper" />
                      <protection id="constants" />
                      <protection id="ctrl flow" />
                      <protection id="harden" />
                      <protection id="invalid metadata" />
                      <protection id="ref proxy" />
                      <protection id="resources" />
                      <protection id="typescramble" />
                      <protection id="rename" />
                      <protection id="watermark" />
                  </rule>
                </module>
             </project>
          '@
          Add-Content -Path "project.crproj" -Value $xml -Encoding UTF8
          
      - name: Check crproj content
        run: Get-Content -Path "D:\\a\\Rubeus\\Rubeus\\project.crproj"

      - name: Create ConfuserEXRubeus
        run:  D:\\a\\Rubeus\\Rubeus\\Confuser.CLI.exe -n D:\\a\\Rubeus\\Rubeus\\project.crproj

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ConfuserExRubeus
          release_name: ConfuserExRubeus
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "D:\\a\\Rubeus\\Rubeus\\Confused\\Rubeus.exe"
          asset_name: ConfuserExRubeus.exe
          asset_content_type: application/octet-stream

# ---------- Build & release InvisibilityCloakConfuserEXRubeus version ----------  
      - name: Checkout InvisibilityCloak
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/InvisibilityCloak

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: invisibilitycloak-artifacts
          path: "D:\\a\\Rubeus\\Rubeus\\InvisibilityCloak.py"

      - name: Checkout Rubeus
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/Rubeus
           
      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: invisibilitycloak-artifacts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: Test InvisibilityCloak
        run: |
          python D:\\a\\Rubeus\\Rubeus\\InvisibilityCloak.py

      - name: Run InvisibilityCloak
        run: |
          python D:\\a\\Rubeus\\Rubeus\\InvisibilityCloak.py -d D:\\a\\Rubeus\\Rubeus -n "InvisibilityCloakRubeus" -m base64
          
      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: invisibilitycloakRubeus-artifacts
          path: "D:\\a\\Rubeus\\Rubeus\\InvisibilityCloakRubeus\\bin\\Release\\InvisibilityCloakRubeus.exe"
  
      - name: Checkout ConfuserEx
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/ConfuserEx

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: invisibilitycloakRubeus-artifacts
          
      - name: Debug Information
        run: |
          Get-ChildItem -Recurse
          Get-Location
          
      - name: Create a .crproj file
        run: |
          $xml = @'
            <project outputDir="D:\\a\\Rubeus\\Rubeus\\Confused" baseDir="D:\\a\\Rubeus\\Rubeus" xmlns="http://confuser.codeplex.com">
                <module path="InvisibilityCloakRubeus.exe">
                    <rule pattern="true" preset="maximum" inherit="false">
                      <protection id="anti debug" />
                      <protection id="anti dump" />
                      <protection id="anti ildasm" />
                      <protection id="anti tamper" />
                      <protection id="constants" />
                      <protection id="ctrl flow" />
                      <protection id="harden" />
                      <protection id="invalid metadata" />
                      <protection id="ref proxy" />
                      <protection id="resources" />
                      <protection id="typescramble" />
                      <protection id="rename" />
                      <protection id="watermark" />
                  </rule>
                </module>
             </project>
          '@
          Add-Content -Path "project.crproj" -Value $xml -Encoding UTF8
          
      - name: Check crproj content
        run: Get-Content -Path "D:\\a\\Rubeus\\Rubeus\\project.crproj"

      - name: Create InvisibilityCloakConfuserEXRubeus
        run:  D:\\a\\Rubeus\\Rubeus\\Confuser.CLI.exe -n D:\\a\\Rubeus\\Rubeus\\project.crproj

      - name: Create Release
        id: create_release_InvisibilityCloakConfuserEXRubeus
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: InvisibilityCloakConfuserEXRubeus
          release_name: InvisibilityCloakConfuserEXRubeus
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_asset_InvisibilityCloakConfuserEXRubeus
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_InvisibilityCloakConfuserEXRubeus.outputs.upload_url }}
          asset_path: "D:\\a\\Rubeus\\Rubeus\\Confused\\InvisibilityCloakRubeus.exe"
          asset_name: InvisibilityCloakConfuserEXRubeus.exe
          asset_content_type: application/octet-stream


