name: confuserExBuilder

on:
  push:
    branches:
      - '*'
  
jobs:
  build_and_release_ConfuserEXRubeus:
    runs-on: windows-2019
    steps:   
   # ---------- Build & release Clean Rubeus version ----------  
      - name: Checkout Rubeus
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/Rubeus

      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rubeus-artifacts
          path: "D:\\a\\Rubeus\\Rubeus\\Rubeus\\bin\\Release\\Rubeus.exe"
          
# ---------- Build & release ConfuserEXRubeus version ----------  
      - name: Checkout ConfuserEx
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/ConfuserEx

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: rubeus-artifacts
          
      - name: Create .crproj file
        run: |
          $outputDir="D:\\a\\Rubeus\\Rubeus\\Rubeus\\bin\\Release"
          $baseDir="D:\\a\\Rubeus\\Rubeus\\Rubeus\\bin\\Release"
          $malware="Rubeus.exe"
          $xml = @'
            <project outputDir="$outputDir\\Confused" baseDir="$baseDir" xmlns="http://confuser.codeplex.com">
                <module path="$malware">
                    <rule pattern="true" preset="maximum" inherit="false">
                      <protection id="anti debug" />
                      <protection id="anti dump" />
                      <protection id="anti ildasm" />
                      <protection id="anti tamper" />
                      <protection id="constants" />
                      <protection id="ctrl flow" />
                      <protection id="harden" />
                      <protection id="invalid metadata" />
                      <protection id="ref proxy" />
                      <protection id="resources" />
                      <protection id="typescramble" />
                      <protection id="rename" />
                      <protection id="watermark" />
                  </rule>
                </module>
             </project>
          '@
          Add-Content -Path "project.crproj" -Value $xml -Encoding UTF8

      - name: Debug Information
        run: |
          Get-ChildItem -Recurse
          Get-Location

#      - name: Test ConfuserEx
#        run:  D:\\a\\Rubeus\\Rubeus\\Confuser.CLI.exe


