name: obfuscationBuilder

on:
  push:
    branches:
      - '*'
  
jobs:
  build_and_release:
    runs-on: windows-2019

    steps:
    
      - name: Checkout InvisibilityCloak
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/InvisibilityCloak

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: invisibilitycloak-artifacts
          path: "D:\\a\\Rubeus\\Rubeus\\InvisibilityCloak.py"

      - name: Checkout Rubeus
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/Rubeus
           
      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'
          
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: invisibilitycloak-artifacts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: Test InvisibilityCloak
        run: |
          python D:\\a\\Rubeus\\Rubeus\\InvisibilityCloak.py

      - name: Run InvisibilityCloak
        run: |
          python D:\\a\\Rubeus\\Rubeus\\InvisibilityCloak.py -d D:\\a\\Rubeus\\Rubeus -n "InvisibilityCloakRubeus" -m base64
          
      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: InvisibilityCloakRubeus
          release_name: InvisibilityCloakRubeus 
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "D:\\a\\Rubeus\\Rubeus\\TotallyLegitTool\\obj\\Release\\InvisibilityCloakRubeus.exe"
          asset_name: InvisibilityCloakRubeus.exe
          asset_content_type: application/octet-stream
          
