# Main workflow file 

name: Main
on:
  workflow_dispatch:
    inputs:
 # -------------------- Obfuscating methods --------------------   
      invisibilitycloak:
        description: 'Obfuscator: InvisibilityCloak'
        type: boolean
        default: true        
        
      confuserEx:
        type: boolean
        default: true
        description: 'Obfuscator: ConfuserEx' 

      invisibilityCloak_encodingMethod:
        type: choice
        description: 'InvisibilityCloak obfuscation method'
        options:
          - base64
          - rot13
          - reverse

 # -------------------- Project directory --------------------
      projectdir:
        description: "Type the project's directory"
        required: true
        default: "D:\\\\a\\\\obfuscation\\\\obfuscation"

# -------------------- New tool's name --------------------
      toolname:
        description: 'Type the name of your new tool'
        required: true
        default: 'Obfuscated'

# -------------------- Tag name & release name --------------------
      release_name:
        description: 'Type the release name'
        required: true
        default: 'clean_version'

      tag_name:
        description: 'Type the tag name'
        required: true
        default: 'clean_version'

jobs:
  Rubeus:
    ### You can use the control flow here to decide if you want to run the Rubeus builder or not
    uses: rsecurity12/rubeus/.github/workflows/rubeus.yml@master
    secrets: inherit   # Same organizations can inherit tokens.


#      token: ${{ secrets.GH_PAT }}


    
