name: Main workflow
on: [workflow_dispatch]

jobs:
  go_run:
    name: Go run
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:      
      - run: echo We warm up
      
      - uses: rsecurity12/Rubeus/.github/actions/sharphound@master
