name: obfuscationBuilder

on:
  push:
    branches:
      - '*'
  
jobs:
  build_and_release:
    runs-on: windows-2019

    steps:
    
      - name: Checkout InvisibilityCloak
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/InvisibilityCloak

      - name: Debug Information
        run: |
          Get-ChildItem -Recurse
          Get-Location
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: invisibilitycloak-artifacts
          path:  D:\a\Rubeus\Rubeus\InvisibilityCloak

      - name: Checkout Rubeus
        uses: actions/checkout@v2
        with:
           repository: rsecurity12/Rubeus
           
      - name: Set up .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.101'
          
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: invisibilitycloak-artifacts

      - name: Debug Information
        run: |
          Get-ChildItem -Recurse
          Get-Location

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Debug Information
        run: |
          Get-ChildItem -Recurse
          Get-Location

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace 'x' with the desired Python version



