######################################### SECTION 1 ################################################
# This section will define the vaviables for GitHub actions
name: obfuscationBuilder
on:
  workflow_dispatch:
    inputs:
      obfuscatorRepositoryName:
        description: "Type the obfuscator repository"
        required: true
        default: "rsecurity12/invisibilityCloak"
        
      optionalObfuscatorRepositoryName:
        description: "Type a second obfuscator repository"
        required: false
        default: "rsecurity12/invisibilityCloak"
        
      redteamRepositoryName:
        description: "Type the RedTeam repository to obfuscate"
        required: true
        default: "rsecurity12/Rubeus"
      projectdir:
        description: 'Type the directory of the project'
        required: true
      toolname:
        description: 'Type the name of your new tool'
        required: true
        default: 'Obfuscated'
#      invisibilitycloak:
#        type: boolean
#        default: true
#        description: InvisibilityCloak
#      confuserex:
#        type: boolean
#        description: ConfuserEx
#      filescanio:
#        type: boolean
#        description: 'FileScan.IO'
      invisbilityCloak_encodingMethod:
        type: choice
        description: 'InvisibilityCloak obfuscation method'
        options:
        - base64
        - rot13
        - reverse

# -------------------- Setup repositories --------------------
jobs:
    obfuscationBuilder:
       runs-on: windows-2019
       steps:
        - name: Checkout obfuscator repository
          uses: actions/checkout@v2
          with:
            repository: "${{ github.event.inputs.obfuscatorRepositoryName }}"

# -------------------- Obfuscation with invisibilityCloak --------------------   
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: invisibilitycloak-artifacts
            path: "${{ github.event.inputs.projectdir }}\\InvisibilityCloak.py"
            
        - name: Debug information
          run: Get-ChildItem .
        




# # -------------------- Build and release InvisibilityCloak --------------------
#         - name: '[InvisibilityCloak] Run' 
#          if: ${{ inputs.invisibilitycloak }}
#            run: |
#               python obfuscation-repo/InvisibilityCloak/InvisibilityCloak.py -d 'target-repo/${{ inputs.projectdir }}' -n '${{ inputs.toolname }}' -m ${{ inputs.method }}
######  
