######################################### SECTION 1 ################################################
# This section will define the vaviables for GitHub actions
name: obfuscationBuilder
on:
  workflow_dispatch:
    inputs:
 # -------------------- Obfuscating methods --------------------   
      invisibilitycloak:
        description: 'Obfuscator: InvisibilityCloak'
        type: boolean
        default: true        
      confuserEx:
        type: boolean
        default: true
        description: 'Obfuscator: ConfuserEx' 

      invisibilityCloak_encodingMethod:
        type: choice
        description: 'InvisibilityCloak obfuscation method'
        options:
        - base64
        - rot13
        - reverse

 # -------------------- RedTeam tools to obfuscate -------------------- 
      Rubeus:
        description: "RedTeam tool: Rubeus"
        type: boolean
        required: false
        default: false
        
      SharpHound:
        description: "RedTeam tool: SharpHound"
        type: boolean
        required: false
        default: false

      SharpLDAPSearch:
        description: "RedTeam tool: SharpLDAPSearch"
        type: boolean
        required: false
        default: false

      SharpUp:
        description: "RedTeam tool: SharpUp"
        type: boolean
        required: false
        default: false

 # -------------------- Project directory --------------------
      projectdir:
        description: "Type the project's directory"
        required: true
        default: "For example: D:\\a\\Rubeus\\Rubeus"

# -------------------- New tool's name --------------------
      toolname:
        description: 'Type the name of your new tool'
        required: true
        default: 'Obfuscated'



# -------------------- Setup repositories --------------------
jobs:
    obfuscationBuilder:
       runs-on: windows-2019
       steps:
        - name: Checkout obfuscator repository
          uses: actions/checkout@v2
          with:
            repository: "${{ github.event.inputs.obfuscatorRepositoryName }}"

# -------------------- Obfuscating Rubeus with invisibilityCloak and/or ConfuserEx --------------------   
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: invisibilitycloak-artifacts
            path: "${{ github.event.inputs.projectdir }}\\InvisibilityCloak.py"

        - name: Checkout Redtool to obfuscate
          uses: actions/checkout@v2
          with:
             repository: "${{ github.event.inputs.redteamRepositoryName }}"

        - name: Set up .NET 7
          if: "contains(github.event.inputs.redteamRepositoryName, 'Rubeus')" 
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '7.0.101'  ## USE DOTNET 4 to build

        - name: Download Artifacts
          uses: actions/download-artifact@v2
          with:
            name: invisibilitycloak-artifacts

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11  
        
        - name: Run InvisibilityCloak
          run: |                                                     
            python "${{ github.event.inputs.projectdir }}\\InvisibilityCloak.py" -d "${{ github.event.inputs.projectdir }}" -n $"{{ github.event.toolname }}" -m  $"{{ github.event.invisibilityCloak_encodingMethod }}"

        - name: Build
          run: |
            dotnet build --configuration Release

        - name: Debug information
          run: Get-ChildItem .



# # -------------------- Build and release InvisibilityCloak --------------------
#         - name: '[InvisibilityCloak] Run' 
#          if: ${{ inputs.invisibilitycloak }}
#            run: |
#               python obfuscation-repo/InvisibilityCloak/InvisibilityCloak.py -d 'target-repo/${{ inputs.projectdir }}' -n '${{ inputs.toolname }}' -m ${{ inputs.method }}
######  
