######################################### SECTION 1 ################################################
# This section will build and release a clean version of Rubeus
name: obfuscationBuilder
on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "Choose repository to build"
        default: "rsecurity12/Rubeus"

jobs:
    obfuscationBuilder:
       runs-on: windows-2019
       
       steps:
        - name: Checkout repository to build
          uses: actions/checkout@v2
          with:
              repository: "${{ github.event.inputs.repositoryName }}"
              ref: master
                      
        - name: Set up .NET 7
          uses: actions/setup-dotnet@v2
          with:
             dotnet-version: '7.0.101'
