on:  # Specifies the event triggering the workflow
  workflow_call:  # Indicates that this is a reusable workflow

######################################### SECTION 2 ################################################
# This section will create 4 types of Rubeus: Rubeus, InvisibilityCloakRubeus, ConfuserExRubeus, InvisibilityCloakConfuserExRubeus
jobs:
    cleanRubeus:
       runs-on: windows-2019
       steps:
# -------------------- Build clean Rubeus --------------------
        - name: Checkout Rubeus
          if: "${{ github.event.inputs.invisibilitycloak == 'false' && github.event.inputs.confuserEx == 'false' }}"
          uses: actions/checkout@v2
          with:
            repository: rsecurity12/Rubeus

        - name: Set up .NET 7
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '7.0.101'  ## USE DOTNET 4 to build

        - name: Build
          run: |
            dotnet build --configuration Release

        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: rubeus-artifacts
            path: "${{ github.event.inputs.projectdir }}\\Rubeus\\bin\\Release\\Rubeus.exe"


    upload-to-release:
      runs-on: ubuntu-latest 
      needs:
      - cleanRubeus
      if: always()  # This ensures the job always runs
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v2
          with:
            name: rubeus-artifacts

        - name: Check location
          run: |
            pwd
            ls

