######################################### SECTION 1 ################################################
# This section will build and release a clean version of Rubeus
name: obfuscationBuilder
on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: "The repository to checkout from"
        required: true
        default: "rsecurity12/Rubeus"
      projectdir:
        description: 'The directory of the project'
        required: true
      toolname:
        description: 'Name of your new tool'
        required: true
        default: 'Obfuscated'
      invisibilitycloak:
        type: boolean
        default: true
        description: InvisibilityCloak
      confuserex:
        type: boolean
        description: ConfuserEx
      filescanio:
        type: boolean
        description: 'FileScan.IO'
      invisbilityCloak_encodingMethod:
        type: choice
        description: 'InvisibilityCloak obfuscation method'
        options:
        - base64
        - rot13
        - reverse

jobs:
    obfuscationBuilder:
       runs-on: windows-2019
       
       steps:
        - name: Checkout repository to build
          uses: actions/checkout@v2
          with:
              repository: "${{ github.event.inputs.repositoryName }}"
              ref: master
                      
        - name: Set up .NET 7
          uses: actions/setup-dotnet@v2
          with:
             dotnet-version: '7.0.101'
