######################################### SECTION 1 ################################################
# This section will build and release a clean version of Rubeus
name: obfuscationBuilder
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Choose Malware to build"
        default: "none"

jobs:
    obfuscationBuilder:
       runs-on: windows-2019
       
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v2
           with:
              repository: "${{ github.event.inputs.name }}"
           
         - name: Set up .NET 7
           uses: actions/setup-dotnet@v2
           with:
              dotnet-version: '7.0.101'
