name: Read Changelog

on:
  push:
    branches:
      - master

jobs:
  read_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: rsecurity12/Rubeus

    - name: List items
      id: list_items
      run: |
        pwd && ls

    - name: Read All Changelog Versions
      run: |
        all_versions=$(grep -oP '^## \[\K[^\]]+' version.md)
        echo "All Changelog Versions: $all_versions"
        highest_version=$(echo "$all_versions" | sort -Vr | head -n 1)
        echo "Highest Changelog Version: $highest_version"
        shell: bash

    - name: Read Latest Changelog Version
      run: |
        latest_version=$(grep -oP '^## \[\K[^\]]+' version.md | head -n 1)
        echo "Latest Changelog Version: $latest_version"
      shell: bash
